---

services:
  grafana:
    container_name: $GRAFANA_CONTAINER_NAME
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GRAFANA_VERSION: $GRAFANA_VERSION
    ports:
      - "$GRAFANA_PORT:3000"
    restart: unless-stopped
    networks:
      network:
        ipv4_address: $GRAFANA_HOST


networks:
  network:
    driver: bridge
    name: $GRAFANA_NETWORK
    ipam:
      config:
        - subnet: $GRAFANA_ADDRES
          gateway: $GRAFANA_GATEWAY
