version: '3'
services:
  grafana:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GRAFANA_VERSION: ${GRAFANA_VERSION}
    ports:
      - "3000:3000"
    restart: unless-stopped
    container_name: grafana